[package]
name = "henji-ai"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2.0.0", features = [] }
tauri-plugin-fs = "2.0.0"
tauri-plugin-dialog = "2.0.0"
tauri-plugin-http = "2.0.0"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }
